---
name: General
"on": pull_request
permissions:
  contents: read
  packages: read
jobs:
  mcvs-general-action:
    strategy:
      matrix:
        args:
          - testing-type: lint-commit
          - testing-type: lint-git
          - testing-type: security-file-system
          - testing-type: yamllint
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6.0.0
      - uses: schubergphilis/mcvs-general-action@v0.5.3
        with:
          testing-type: ${{ matrix.args.testing-type }}
